## GERAL
background            #0b0f1a
foreground            #c8c8d6
cursor                #ce4ea9
cursor_text_color     #0b0f1a
selection_background  #ce4ea9
selection_foreground  #0b0f1a

## BORDAS E GUI
active_border_color   #ce4ea9
inactive_border_color #332642
bell_border_color     #ffeab9
visual_bell_color     #ce4ea9
url_color             #77bdfa
scrollbar_color       #332642

## TABS (se estiver usando)
tab_bar_background    #0b0f1a
active_tab_background #ce4ea9
active_tab_foreground #0b0f1a
inactive_tab_background #1e1e2f
inactive_tab_foreground #c8c8d6

## CORES ANSI
color0  #0b0f1a
color1  #ce4ea9
color2  #8fe6c6
color3  #ffeab9
color4  #77bdfa
color5  #b083d3
color6  #80e8dc
color7  #ffffff

## CORES BRILHANTES
color8  #3e3e5c
color9  #ff75be
color10 #b8f7da
color11 #fff5c6
color12 #8dcfff
color13 #d5a0f7
color14 #a0f0eb
color15 #f0f0f0
