#################
### AUTOSTART ###
#################
# Autostart necessary processes (like notifications daemons, status bars, etc.)


# exec-once = nm-applet &
exec-once = waypaper --restore
exec-once = hyprpaper 
exec-once = waybar
exec-once = blueman-applet
exec-once = hypridle
exec-once = swaync
exec-once = $terminal


