
# #######################################################################################
#           __                                                
#          / /_  __  ______  _________  ____ _____  ___  _____
#         / __ \/ / / / __ \/ ___/ __ \/ __ `/ __ \/ _ \/ ___/
#        / / / / /_/ / /_/ / /  / /_/ / /_/ / /_/ /  __/ /    
#       /_/ /_/\__, / .___/_/  / .___/\__,_/ .___/\___/_/       by M4tzG °w°    
#             /____/_/        /_/         /_/             
#                                                                             *font Slant
# #######################################################################################

# source = theme.

preload = /home/matheus/.config/hypr/themes/_default/wallps/miku_2.jpg

#set the default wallpaper
wallpaper = ,/home/matheus/.config/hypr/themes/_default/wallps/miku_2.jpg


#if more than one monitor in use, can load a 2nd image
# wallpaper = monitor2,/path/to/next_image.png
# .. more monitors

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off

