
# #######################################################################################
#           __                                                
#          / /_  __  ______  _________  ____ _____  ___  _____
#         / __ \/ / / / __ \/ ___/ __ \/ __ `/ __ \/ _ \/ ___/
#        / / / / /_/ / /_/ / /  / /_/ / /_/ / /_/ /  __/ /    
#       /_/ /_/\__, / .___/_/  / .___/\__,_/ .___/\___/_/       by M4tzG °w°    
#             /____/_/        /_/         /_/             
#                                                                             *font Slant
# #######################################################################################

# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/themes/_default/wallps/554306.jpg
    fit_mode = cover

}

splash = true
