##############################
### WINDOWS AND WORKSPACES ###
##############################

# Example windowrule v1
# windowrule = float, ^(kitty)$
# windowrule = size 60% 70%, ^(ranger)$

# Example windowrule v2
# Regras só para o terminal com título "float-terminal"
windowrulev2 = float,title:^(float-terminal)$
windowrulev2 = size 1000 600,title:^(float-terminal)$
windowrulev2 = center,title:^(float-terminal)$

# windowrulev2 = tag:ranger, class:kitty, floating, size 60% 70%

# Forçar arredondamento para o Rofi

# layerrule = blur, wofi/rofi
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
