#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
WIDGETS="profile system uptime music apps logout sleep reboot poweroff folders"

close_dash() {
    # Fecha cada widget individualmente para evitar o travamento do daemon

    ${EWW} --config "$CFG" kill

    rm -f "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--bw" ]]; then
	close_dash && bitwarden &

elif [[ "$1" == "--kr" ]]; then
	close_dash && kate &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty &

elif [[ "$1" == "--fm" ]]; then
	close_dash && thunar ~ &

elif [[ "$1" == "--kt" ]]; then
	close_dash && krita

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--st" ]]; then
	close_dash && steam &

fi
